### ISSUE TITLE
Deploy via ArgoCD Application fails

### ISSUE THREAD

**Issue by kagarlickij** [rdvansloten/cert-manager-key-vault-sync#22]
Hi there, I have to use ArgoCD Application to deploy `cert-manager-key-vault-sync`,  to use my custom `values.yaml` I have to create my chart on top of `cert-manager-key-vault-sync-chart`,
Here's my Application.yaml: 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-key-vault-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kagarlickij/cert-mgr.git
    targetRevision: main
    path: charts/cert-manager-key-vault-sync
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-key-vault-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

Chart.yaml:
```
apiVersion: v2
name: cert-manager-key-vault-sync-chart-fork
version: 1.2.1
dependencies:
  - name: cert-manager-key-vault-sync-chart
    version: v1.2.1
    repository: oci://docker.io/rdvansloten
```

values.yaml:
```
image:
  repository: docker.io/rdvansloten/cert-manager-key-vault-sync
  tag: v1.2.0
  pullPolicy: Always

replicaCount: 1

certificates:
  annotation: "cert-manager.io/certificate-name"
  useNamespaces: "false"
  checkInterval: 600
  filter: "*"

prometheus:
  enabled: false

azure:
  keyVaultName: "kag-test-akv"
  workloadIdentity:
    clientId: "f583f2a2-4641-482c-ae8a-59d0d650cdb2"
    subscriptionId: "8a8482bc-56bd-4a34-ba35-f260245eb1b9"
    tenantId: "daf940fc-d5ed-4f51-b759-e3e859111d34"
    clientSecret: "cert-manager-key-vault-sync-secret"
```

When I'm applying `Application.yaml` in ArgoCD I'm getting:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc
error: code = Unknown desc = failed to set app instance tracking info on
manifest: failed to get annotations for /V1, Kind=ServiceAccount cert-manager-key-vault-sync/cert-manager-key-vault-sync:
.metadata.annotations accessor error: contains non-string value in the map under key "azure.workload. identity/tenant-id": <nil> is of the type ‹nil>, expected string
```

Any clue why it could happen and how to fix it? 
Thanks!
